node('tomcat-user') {
      stage ('git checkout stage') {
            checkout scm
    }
     stage ('build/push') {
    docker.withRegistry('https://index.docker.io/v1/', 'innocent2020') {
    def customImage = docker.build("innocent2020/my-jenkins-image:${env.BUILD_ID}")

   customImage.push()
    }
  }
     stage('start jenkins') {
        def jenkins = docker.image('innocent2020/my-jenkins-image:17').run("-p 7000:8080 -p 50000:50000") 
        
         jenkins.inside {
           sh 'touch /var/run/testinn.txt'  
        }    
     }             

}
